### ISSUE TITLE
exception when trying to repeat a scenario that includes a listen step one more time

### ISSUE THREAD

**Issue by xenry** [VIP-Logic/NBomber#32]
### Steps to reproduce
- run the simple push scenario (c#)
- when run finishes and and you are asked to repeat the same scenario one more time - type 'y'
- observe exception

```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: warm_up_flow
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at <StartupCode$NBomber>.$Scenario.Init@57.Invoke(StepListener x) in F:\code\NBomber\src\NBomber\Domain\Scenario.fs:line 57
   at NBomber.StepListeners.Init(StepListener[] items) in F:\code\NBomber\src\NBomber\Domain\Scenario.fs:line 57
   at NBomber.TestFlowModule.initFlow@112-2.Invoke(ListenerStep listStep) in F:\code\NBomber\src\NBomber\Domain\Scenario.fs:line 112
   at NBomber.TestFlowModule.initFlow(TestFlow flow) in F:\code\NBomber\src\NBomber\Domain\Scenario.fs:line 112
   at NBomber.ScenarioRunner.runScenario@27.Invoke(TestFlow flow) in F:\code\NBomber\src\NBomber\ScenarioRunner.fs:line 27
   at NBomber.ScenarioRunner.runScenario(Scenario scenario) in F:\code\NBomber\src\NBomber\ScenarioRunner.fs:line 27
   at NBomber.ScenarioRunner.Run(Scenario scenario) in F:\code\NBomber\src\NBomber\ScenarioRunner.fs:line 18
   at NBomber.Examples.CSharp.Program.Main(String[] args) in F:\code\NBomber\examples\NBomber.Examples.CSharp\Program.cs:line 18
```
### Possible fix
I think that when initing the listeners, the listeners dictionary should be cleaned first.

**Comment by AntyaDev** [comment]
thank you @xenry, we will take a look.
