### ISSUE TITLE
Exception while running first example

### ISSUE THREAD

**Issue by ggercman** [VIP-Logic/NBomber#573]
Got exception at the end of running first demo.
How to reproduce: 

csproj:
-------
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NBomber" Version="4.1.2" />
    <PackageReference Include="NBomber.Http" Version="4.1.1" />
  </ItemGroup>
</Project>
```
program.cs: 
------
```
using NBomber.CSharp;

var scenario = Scenario.Create("hello_world_scenario", async context =>
{
    await Task.Delay(1_000);

    return Response.Ok();
})
.WithoutWarmUp()
.WithLoadSimulations(
    Simulation.RampingInject(rate: 50, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(1)),
    Simulation.Inject(rate: 50, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(1)),
    Simulation.InjectRandom(minRate: 50, maxRate: 10, interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromSeconds(30))
);

NBomberRunner
    .RegisterScenarios(scenario)
    .Run();
```

`

Exception at the end of running scenarios.

```
'minValue' cannot be greater than maxValue. Arg_ParamName_Name

   at System.Random.ThrowMinMaxValueSwapped() in /_/src/libraries/System.Private.CoreLib/src/System/Random.cs:line 198
   at System.Random.Next(Int32 minValue, Int32 maxValue) in /_/src/libraries/System.Private.CoreLib/src/System/Random.cs:line 94
   at NBomber.Domain.Scheduler.ScenarioScheduler.clo@159-8.MoveNext() in /home/runner/work/NBomber/NBomber/src/NBomber/Domain/Scheduler/ScenarioScheduler.fs:line 191
   at <StartupCode$NBomber>.$TestHost.clo@74-18.MoveNext() in /home/runner/work/NBomber/NBomber/src/NBomber/DomainServices/TestHost/TestHost.fs:line 93
   at <StartupCode$NBomber>.$TestHost.StopTest@202.MoveNext() in /home/runner/work/NBomber/NBomber/src/NBomber/DomainServices/TestHost/TestHost.fs:line 216
```

**Comment by AntyaDev** [comment]
Hi @ggercman 

Is it easy to reproduce? 
I have tried but have had no luck...

**Comment by ggercman** [comment]
Actually I get exception on each execution.
![image](https://user-images.githubusercontent.com/17136896/230475641-9f80bc4b-fb70-4292-9cb1-0fc47de78b59.png)

**Comment by AntyaDev** [comment]
@ggercman 
I can't reproduce this behavior.
I copied your snippet, pasted it into the CSharpProd project, and tried reproducing it but was unsuccessful.

**Comment by AntyaDev** [comment]
@ggercman 
Finally, I reproduced it, I just needed to wait more than 2 mins.
Btw, why do you specify: minRate: 50, maxRate: 10? I mean why maxRate is lower than minRate?

**Comment by AntyaDev** [comment]
I think I need to add a validation that will check: minRate < maxRate

**Comment by ggercman** [comment]
I probably copied from one of provided examples. This one https://github.com/PragmaticFlow/NBomber/blob/dev/examples/CSharpProd/HelloWorld/LoadSimulation/ScenarioInjectRate.cs

**Comment by AntyaDev** [comment]
ah sorry, it's my mistake.
