### ISSUE TITLE
Unhandled exception: MetricsStatsActor failed

### ISSUE THREAD

**Issue by EduardGeorgiev** [VIP-Logic/NBomber#695]
NBomber was stuck for 30 minutes on finalizing scenarios.
I checked the logs:
```
2024-05-15 17:00:51.805 +01:00 [INF] [ThreadId:11] Plugins: no plugins were loaded
2024-05-15 17:00:51.806 +01:00 [INF] [ThreadId:11] Reporting sinks: no reporting sinks were loaded
2024-05-15 17:00:51.807 +01:00 [INF] [ThreadId:11] Starting init...
2024-05-15 17:00:51.822 +01:00 [INF] [ThreadId:11] Target scenarios: GPS Journey Ancillaries Load Test
2024-05-15 17:00:51.828 +01:00 [INF] [ThreadId:11] Init finished
2024-05-15 17:00:51.873 +01:00 [INF] [ThreadId:11] Starting bombing...
2024-05-15 17:12:54.054 +01:00 [INF] [ThreadId:37] Waiting on scenarios completion...
2024-05-15 17:26:32.867 +01:00 [FTL] [ThreadId:34] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:26:33.728 +01:00 [FTL] [ThreadId:28] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:26:41.062 +01:00 [FTL] [ThreadId:450] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:26:41.073 +01:00 [FTL] [ThreadId:450] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:26:41.076 +01:00 [FTL] [ThreadId:450] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:26:41.088 +01:00 [FTL] [ThreadId:450] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:26:41.099 +01:00 [FTL] [ThreadId:450] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:26:41.106 +01:00 [FTL] [ThreadId:450] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:34.718 +01:00 [FTL] [ThreadId:35] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:34.741 +01:00 [FTL] [ThreadId:35] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:34.765 +01:00 [FTL] [ThreadId:35] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:40.822 +01:00 [FTL] [ThreadId:33] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:40.836 +01:00 [FTL] [ThreadId:33] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:40.846 +01:00 [FTL] [ThreadId:33] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:40.873 +01:00 [FTL] [ThreadId:33] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:40.887 +01:00 [FTL] [ThreadId:33] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:40.912 +01:00 [FTL] [ThreadId:33] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2024-05-15 17:36:40.937 +01:00 [FTL] [ThreadId:33] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.Utilities.Bitwise.Log2(Int32 i)
   at HdrHistogram.Utilities.Bitwise.NumberOfLeadingZeros(Int64 value)
   at HdrHistogram.HistogramBase.RecordSingleValue(Int64 value)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
```
Sadly no reports were output and thus the test results were lost.

**Comment by AntyaDev** [comment]
Hi @EduardGeorgiev ,
Thank you for this information. Is it easy to reproduce? If yes what steps to be done to achieve the same effect?

**Comment by EduardGeorgiev** [comment]
Hello @AntyaDev . I am unsure of exactly what caused it, but here's some info:
In the beginning I set:
```
        GCSettings.LatencyMode = GCLatencyMode.SustainedLowLatency;
```
Load Simulations:
```
        var trafficPerSecond = 150;
            Simulation.RampingInject(rate: (int)(trafficPerSecond * 1f), interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(1)), // 66% => 100%
            Simulation.Inject(rate: (int)(trafficPerSecond * 1f), interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(9)), // 100%
            Simulation.RampingInject(rate: (int)(trafficPerSecond * 2f), interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(1)), // 100% => 200%
            Simulation.Inject(rate: (int)(trafficPerSecond * 2f), interval: TimeSpan.FromSeconds(1), during: TimeSpan.FromMinutes(1)) // 200% for extra confidence
```
The scenario is .WithMaxFailCount(500000), I had more than 30K failures by the end of it.  
My internet was slow, I believe it was still bombing even 30minutes after "Waiting on scenarios completion...", which was peculiar to me, as I was hoping NBomber to have some safeguards to alert me in case the requests are going out too slow for the requested bombing speed.
My config:
```
{
  "TestSuite": "Ticket Options Tests",
  "TestName": "Ticket Options Load Test",
  "GlobalSettings": {
    "ReportFormats": [ "Html", "Txt", "Csv", "Md" ]
  }
}
```
Runner:
```
        var fileDate = DateTimeOffset.Now.ToUnixTimeSeconds().ToString();
        var runner = NBomberRunner
            .RegisterScenarios(scenarioTicketOptionsLoadTest)
            .LoadConfig("config.json")
            .WithReportFolder(Path.Combine(resultsDir, fileDate))
            .WithReportFileName($"report_{fileDate}")
            .WithLoggerConfig(() =>
                new LoggerConfiguration()
                    .MinimumLevel.Debug()
                    .WriteTo.File(
                        path: Path.Combine(solutionDir, "logs", "log.txt"),
                        outputTemplate:
                        "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [ThreadId:{ThreadId}] {Message:lj}{NewLine}{Exception}",
                        rollingInterval: RollingInterval.Day)
            )
            .WithLicense(Settings.LicenseKey);
```

That's about it.

**Comment by AntyaDev** [comment]
Thanks,
We will try to reproduce it. And I probably will ask more questions :)

**Comment by AntyaDev** [comment]
Hi @EduardGeorgiev 
I'm sorry for not getting back to you sooner.
Could you let me know if you saw this exception in the latest versions?

**Comment by EduardGeorgiev** [comment]
@AntyaDev No worries. I was using the latest version available at the time, I haven't used it since then, so I have no info on newer versions.

**Comment by AntyaDev** [comment]
Found one case with redis example:

```
2025-02-13 13:05:53.685 +02:00 [INF] [ThreadId:1] Target scenarios: redis_init, redis_read, redis_write
2025-02-13 13:05:53.688 +02:00 [INF] [ThreadId:1] Start init scenario: redis_init
2025-02-13 13:07:09.182 +02:00 [INF] [ThreadId:1] Start init scenario: redis_read
2025-02-13 13:07:09.188 +02:00 [INF] [ThreadId:1] Start init scenario: redis_write
2025-02-13 13:07:09.195 +02:00 [INF] [ThreadId:1] Init finished
2025-02-13 13:07:09.215 +02:00 [INF] [ThreadId:1] Starting warm up...
2025-02-13 13:07:09.216 +02:00 [INF] [ThreadId:1] Warm up for scenarios: redis_read, redis_write
2025-02-13 13:07:09.222 +02:00 [INF] [ThreadId:1] Warm up duration: 00:00:05
2025-02-13 13:07:15.263 +02:00 [INF] [ThreadId:39] Starting bombing...
2025-02-13 13:10:35.423 +02:00 [FTL] [ThreadId:7] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.LongHistogram.IncrementCountAtIndex(Int32 index)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2025-02-13 13:10:40.350 +02:00 [FTL] [ThreadId:30] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.LongHistogram.IncrementCountAtIndex(Int32 index)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2025-02-13 13:10:45.332 +02:00 [FTL] [ThreadId:47] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.LongHistogram.IncrementCountAtIndex(Int32 index)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2025-02-13 13:10:46.864 +02:00 [INF] [ThreadId:33] Waiting on scenarios completion...
2025-02-13 13:10:50.334 +02:00 [FTL] [ThreadId:47] Unhandled exception: MetricsStatsActor failed: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HdrHistogram.LongHistogram.IncrementCountAtIndex(Int32 index)
   at NBomber.Domain.Stats.MetricsStatsActor.clo@128-6.MoveNext()
2025-02-13 13:10:50.868 +02:00 [INF] [ThreadId:47] Stopping scenarios...
2025-02-13 13:10:50.870 +02:00 [INF] [ThreadId:47] Calculating final statistics...

```
